# Generated by Django 4.1.4 on 2023-10-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='confirmation_token',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
